# Force re-index: trivial change to make workflow appear in Actions tab
name: Agent Smoke Test

on:
  workflow_dispatch:
    inputs:
      agent_url:
        description: 'Agent URL to test (leave empty to auto-detect)'
        required: false
        default: ''
        type: string

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies (root)
        run: pnpm install

      - name: Install dependencies (extension)
        run: |
          cd apps/extension
          pnpm install
          cd ../..

      - name: Build extension
        run: |
          cd apps/extension
          pnpm run build
          cd ../..

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Make script executable
        run: chmod +x scripts/agent-smoke-test.sh

      - name: Run agent smoke test
        env:
          AGENT_URL: ${{ github.event.inputs.agent_url }}
        run: ./scripts/agent-smoke-test.sh

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: agent-smoke-results
          path: |
            test-results/
            playwright-report/ 