name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  backend-deploy:
    name: Build & Deploy Backend
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check required secrets
        run: |
          if [ -z "${{ secrets.GCP_SA_KEY }}" ] || [ -z "${{ secrets.GCP_PROJECT_ID }}" ] || [ -z "${{ secrets.GEMINI_API_KEY }}" ] || [ -z "${{ secrets.DAILY_API_KEY }}" ]; then
            echo "::error::Missing required secret: GCP_SA_KEY, GCP_PROJECT_ID, GEMINI_API_KEY, or DAILY_API_KEY" && exit 1
          fi

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure gcloud
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set run/region us-central1

      - name: Build backend container
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/peazy-agent:${{ github.sha }} gemini-multimodal-live-demo/server/

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy peazy-agent \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/peazy-agent:${{ github.sha }} \
            --region us-central1 \
            --min-instances 1 \
            --max-instances 3 \
            --set-secrets "GEMINI_API_KEY=projects/${{ secrets.GCP_PROJECT_ID }}/secrets/GEMINI_API_KEY:latest,DAILY_API_KEY=projects/${{ secrets.GCP_PROJECT_ID }}/secrets/DAILY_API_KEY:latest" \
            --timeout 900s

  frontend-deploy:
    name: Build & Upload Frontend
    runs-on: ubuntu-latest
    needs: backend-deploy
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check required secrets
        run: |
          if [ -z "${{ secrets.GCP_SA_KEY }}" ] || [ -z "${{ secrets.GCP_PROJECT_ID }}" ]; then
            echo "::error::Missing required secret: GCP_SA_KEY or GCP_PROJECT_ID" && exit 1
          fi

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build frontend
        run: |
          cd gemini-multimodal-live-demo/client
          npm ci
          npm run build

      - name: Upload to GCS
        run: |
          BUCKET=${{ secrets.GCP_PROJECT_ID }}-web
          gsutil mb -l us-central1 -p ${{ secrets.GCP_PROJECT_ID }} gs://$BUCKET || true
          gsutil -m rsync -r -c gemini-multimodal-live-demo/client/dist gs://$BUCKET
          gsutil -m setmeta -h "Cache-Control:public,max-age=3600" gs://$BUCKET/**

      - name: Output URLs
        run: |
          echo "Cloud Run URL: https://console.cloud.google.com/run/detail/us-central1/peazy-agent/overview?project=${{ secrets.GCP_PROJECT_ID }}"
          echo "Frontend URL: https://${{ secrets.GCP_PROJECT_ID }}-web.storage.googleapis.com/index.html" 